### ISSUE TITLE
给个例子,

### ISSUE THREAD

**Issue by f4nff** [xausky/ShadowsocksGostPlugin#1]
比如我想用

```
-F=kcp://www.baidu.com:443?ip=2.2.2.2

-F=mwss://www.baidu.com:443?path=/11.html&ip=1.1.1.1
```

怎么写,我并不想用ss协议,

**Comment by f4nff** [comment]
别搞插件,直接搞个输入参数的app出来呀,

搞一个-L=:1090 -F=~

**Comment by xausky** [comment]
`-F=kcp://www.baidu.com:443?ip=2.2.2.2 -F=mwss://www.baidu.com:443?path=/11.html&ip=1.1.1.1`这个填到插件配置里面，上面服务器和端口随便填，密码：s123456，加密：chacha20，启用小飞机，可以用了

**Comment by xausky** [comment]
搞可以输入参数的APP你还得配置系统的代理，还不能选择应用绕过，还不能自动根据GFWLIST过滤，用插件可以直接使用小飞机的一些便利的特性
