### ISSUE TITLE
Android10 报错libss- local exits too fast

### ISSUE THREAD

**Issue by ddgweb** [xausky/ShadowsocksGostPlugin#10]
![微信图片_20190926203814.jpg](https://i.loli.net/2019/09/26/ri1fCvO8kQAtox5.jpg)

Android10 报错libss- local exits too fast

MIUI10 刚升级的

**Comment by xausky** [comment]
已经在 [2.8.1-2 版本](https://github.com/xausky/ShadowsocksGostPlugin/releases/tag/v2.8.1-2) 修复
