### ISSUE TITLE
插件无法正常工作

### ISSUE THREAD

**Issue by lazyii** [xausky/ShadowsocksGostPlugin#11]
服务端：
gost 2.8.1 (go1.12 windows/amd64)
ip：172.0.0.200
客户端：
ss:4.8.5
plugin:2.8.1
ip：172.0.0.201

服务端启动命令：gost -L=ss+ws://chacha20:password@:8338
客户端配置：
******
服务器：172.0.0.200
远程端口：8338
密码：password
加密：chacha20
插件：-F ss+ws://chacha20:password@172.0.0.200:8338
******

客户端无法连接网络，服务端日志：

2019/11/04 10:23:07 ss.go:121: [ss] 172.0.0.201:54991 -> ss+ws://:8338 -> 19.151.37.199:28325
2019/11/04 10:23:07 ss.go:161: [route] 172.0.0.201:54991 -> ss+ws://:8338 -> 19.151.37.199:28325
2019/11/04 10:23:07 ss.go:121: [ss] 172.0.0.201:54992 -> ss+ws://:8338 -> [78ee:2a7:cd28:eeba:b5dd:3bca:9e2:4184]:31164
2019/11/04 10:23:07 ss.go:161: [route] 172.0.0.201:54992 -> ss+ws://:8338 -> [78ee:2a7:cd28:eeba:b5dd:3bca:9e2:4184]:31164
2019/11/04 10:23:10 ss.go:171: [ss] 172.0.0.201:54959 -> 172.30.5.49:8338 : dial tcp 219.167.146.87:58878: i/o timeout
2019/11/04 10:23:12 ss.go:171: [ss] 172.0.0.201:54976 -> 172.30.5.49:8338 : dial tcp 200.187.117.225:38341: i/o timeout
2019/11/04 10:23:12 ss.go:171: [ss] 172.0.0.201:54991 -> 172.30.5.49:8338 : dial tcp 19.151.37.199:28325: i/o timeout
2019/11/04 10:23:12 ss.go:171: [ss] 172.0.0.201:54992 -> 172.30.5.49:8338 : dial tcp [78ee:2a7:cd28:eeba:b5dd:3bca:9e2:4184]:31164: i/o timeout
2019/11/04 10:23:15 ws.go:413: [ws] 172.0.0.201:55033 -> [::]:8338
2019/11/04 10:23:15 ss.go:121: [ss] 172.0.0.201:55033 -> ss+ws://:8338 -> 214.114.138.85:55257
2019/11/04 10:23:15 ss.go:161: [route] 172.0.0.201:55033 -> ss+ws://:8338 -> 214.114.138.85:55257
2019/11/04 10:23:20 ss.go:171: [ss] 172.0.0.201:55033 -> 172.30.5.49:8338 : dial tcp 214.114.138.85:55257: i/o timeout
2019/11/04 10:23:43 ws.go:413: [ws] 172.0.0.201:55038 -> [::]:8338
2019/11/04 10:23:43 ss.go:121: [ss] 172.0.0.201:55038 -> ss+ws://:8338 -> [ad78:9cac:6ef4:da1:7329:82fe:b7fb:e9c6]:55621
2019/11/04 10:23:43 ss.go:161: [route] 172.0.0.201:55038 -> ss+ws://:8338 -> [ad78:9cac:6ef4:da1:7329:82fe:b7fb:e9c6]:55621
2019/11/04 10:23:48 ss.go:171: [ss] 172.0.0.201:55038 -> 172.30.5.49:8338 : dial tcp [ad78:9cac:6ef4:da1:7329:82fe:b7fb:e9c6]:55621: i/o timeout
2019/11/04 10:23:48 ws.go:413: [ws] 172.0.0.201:55041 -> [::]:8338
2019/11/04 10:23:48 ss.go:121: [ss] 172.0.0.201:55041 -> ss+ws://:8338 -> 97.100.186.88:52766
2019/11/04 10:23:48 ss.go:161: [route] 172.0.0.201:55041 -> ss+ws://:8338 -> 97.100.186.88:52766
2019/11/04 10:23:53 ss.go:171: [ss] 172.0.0.201:55041 -> 172.30.5.49:8338 : dial tcp 97.100.186.88:52766: i/o timeout

**Comment by xausky** [comment]
2.8.1 版本的默认加密方式是 `rc4-md5` 默认密码是 `gost` 如果不行看日志可能是和服务器网络不联通

**Comment by lazyii** [comment]
加密方式我都是选择的chacha20,server端安卓app里的设置的都是。
而且当我用pc客户端执行：gost -F ss+ws://chacha20:password@172.0.0.200:8338 的时候是可以正常代理的。所以才怀疑是不是插件有问题。

**Comment by xausky** [comment]
安卓端 插件参数里面要写 chacha20:password 但是ss的客户端配置里面必须固定 rc4-md5:gost

**Comment by lazyii** [comment]
已经完美解决，是我理解错了。已经按照大佬的方法完美代理。大佬牛皮<破音~~
