### ISSUE TITLE
建议不要用114DNS

### ISSUE THREAD

**Issue by updateserver** [xausky/ShadowsocksGostPlugin#13]
原因如下:
一，访问如下网址查看
http://www.dwhd.org/20150720_221719.html
二，114DNS篡改了记录(重要)
验证如下:
nslookup xxx.herokuapp.com 119.29.29.29
可以返回正常结果。
nslookup xxx.herokuapp.com 114.114.114.114
什么都没有。

**Comment by updateserver** [comment]
> 原因如下:
> 一，访问如下网址查看
> http://www.dwhd.org/20150720_221719.html
> 二，114DNS篡改了记录(重要)
> 验证如下:
> nslookup xxx.herokuapp.com 119.29.29.29
> 可以返回正常结果。
> nslookup xxx.herokuapp.com 114.114.114.114
> 什么都没有。

另我提了PR
https://github.com/xausky/gost/pull/1/files

**Comment by xausky** [comment]
干的漂亮，国内这个网络环境真是夹缝里面求生存了，后面会发布 2.8.1-2 来合并这个提交

**Comment by xausky** [comment]
https://github.com/xausky/ShadowsocksGostPlugin/releases/tag/v2.8.1-3
