### ISSUE TITLE
[BUG]等号问题

### ISSUE THREAD

**Issue by updateserver** [xausky/ShadowsocksGostPlugin#14]
当插件参数里有=(等号)时，会变成\\=导致参数无效
插件参数:-F=ss+wss://chacha20:xxx@xxx.herokuapp.com:443?path=xxx
-F=ss+wss://chacha20:xxx@xxx.herokuapp.com:443?path=xxx会变成-F=ss+wss://chacha20:xxx@xxx.herokuapp.com:443?path\\=xxx

**Comment by xausky** [comment]
临时解决办法是改为 `-F ss+wss://chacha20:xxx@xxx.herokuapp.com:443?path=xxx`，后面看看怎么修复，这个是SS Android 客户端的行为

**Comment by updateserver** [comment]
> 临时解决办法是改为 `-F ss+wss://chacha20:xxx@xxx.herokuapp.com:443?path=xxx`，这个是SS Android 客户端的行为，也不好修复，我再说明里面写一下吧。

好的。

**Comment by updateserver** [comment]
> 临时解决办法是改为 `-F ss+wss://chacha20:xxx@xxx.herokuapp.com:443?path=xxx`，这个是SS Android 客户端的行为，也不好修复，我再说明里面写一下吧。

已提PR解决了如下问题:
简单修复下shadowsocks Android版传入参数=变成\=而无效的问题。
https://github.com/xausky/gost/pull/2/files
https://github.com/xausky/gost/pull/2
