### ISSUE TITLE
提示未知插件，需要怎么解决？

### ISSUE THREAD

**Issue by 03128crz** [xausky/ShadowsocksGostPlugin#15]
PC上是以下的设置，然后启动pc 版的ss客户端是可以连接的：
gost.exe -L ss://aes-128-cfb:passcode@:1984 -F https://用户名:密码@域名:443

在Android上我如下设置，不行：
![image](https://user-images.githubusercontent.com/3424553/70765456-d0490380-1d95-11ea-90c3-e74407a40bf3.png)

**Comment by xausky** [comment]
可以通过 adb logcat 查看日志

**Comment by 03128crz** [comment]
> 可以通过 adb logcat 查看日志

我手机上ss的其它配置有问题吗？

**Comment by xausky** [comment]
看上去没啥问题

**Comment by jiyj1998** [comment]
@03128crz 问题解决了么？我也遇到了
