### ISSUE TITLE
请教参数配置的问题

### ISSUE THREAD

**Issue by Nekowei** [xausky/ShadowsocksGostPlugin#16]
我想复用我在windows端的配置：
-L ss://aes-256-cfb:localpassword@:localport -F https://username:password@ip:port
然后windows上的ss就可以配置成：
ip：127.0.0.1
port：localport
pasword：localpassword
但是我按照相似的方式在安卓上配置行不通。

说明中提到-L参数会自动配置，那么请问在安卓的ss配置里该如何填写ip，port等信息？

**Comment by xausky** [comment]
ip port 可以随意填写，密码写 gost，加密选 rc4-md5 就可以，配置填写 -F https://username:password@ip:port

**Comment by Nekowei** [comment]
噢可以了，感谢！
