### ISSUE TITLE
ss和gost之间的通讯问题

### ISSUE THREAD

**Issue by CNetizen** [xausky/ShadowsocksGostPlugin#17]
shadowsocks和gost之间是用domainsocket通讯的吗？

**Comment by xausky** [comment]
是用 TCP Socket 通信的，SS 会传端口过来，GOST 监听那个端口通过 TCP 通信。
这里面有比较详细的介绍：https://shadowsocks.org/en/spec/Plugin.html

**Comment by xausky** [comment]
是用 TCP Socket 通信的，SS 会传端口过来，GOST 监听那个端口通过 TCP 通信。
这里面有比较详细的介绍：https://shadowsocks.org/en/spec/Plugin.html

**Comment by CNetizen** [comment]
感谢，看了一下文档和你fork的gost源码，搞清楚了。
做成SS插件的这种形式的确很棒，省去了VPN和路由的实现。如果精力允许希望能跟上gost官方更新的节奏并提交到play store。
