### ISSUE TITLE
后台服务启动失败：无法连接远程服务器：Failed to connect to socks 123.a.....

### ISSUE THREAD

**Issue by 03128crz** [xausky/ShadowsocksGostPlugin#18]
PC上：
gost -L ss://aes-128-cfb:passcode@:1984 -F 'https://USER:PASS@DOMAIN:443'

手机SS上IP和远程端口随便填，密码：gost，加密方式RC-MD5.
gost插件配置 -F https://USER:PASS@DOMAIN:443
出现后台服务启动失败。请问怎么回事，谢谢~

**Comment by xausky** [comment]
不支持 https 代理，转换为　socket 代理

**Comment by xausky** [comment]
你这个在 PC 上的应该也无法配置给 ShadowSocket 用。

**Comment by hacstII** [comment]
手机系统默认不允许插件自启动的话也会出这个问题
以EMUI为例解决方法是 设置->应用->应用启动管理->ShadowsocksGostPlugin->手动管理->允许关联启动
