### ISSUE TITLE
支持https的代理吗？

### ISSUE THREAD

**Issue by haibinpark** [xausky/ShadowsocksGostPlugin#19]
PC端: 
gost -L http2://0.0.0.0:443

插件配置
-F https://xxx:xxx@proxy.demo.com:443
ss配置
加密方式: CHACHA20
密码: ss123456
可以连接上，但是打不开网页呢。

机器型号: MIX2
系统信息: MIUI 11 20.1.2 | 开发板

**Comment by xausky** [comment]
不支持的，无法将 socket 流量代理到 https，你可以直接设置到手机WIFI的代理里面。
