### ISSUE TITLE
请问为什么无法使用？

### ISSUE THREAD

**Issue by wizos** [xausky/ShadowsocksGostPlugin#2]
您好，我把原生的配置填好，又填了一次插件的配置【-F=ss+mws://chacha20:xxx@yyy.herokuapp.com:80】后，为什么还是无法使用呢？谢谢

**Comment by xausky** [comment]
正常情况应该可以使用了注意小飞机上面的密码要填: ss123456 加密方式填：chacha20，服务器和端口可以随意填写

**Comment by wizos** [comment]
谢谢！

**Comment by updateserver** [comment]
> 谢谢！

因该是这个的锅(https://github.com/xausky/ShadowsocksGostPlugin/issues/13)

**Comment by updateserver** [comment]
> 谢谢！

我也无法使用，原因找到了。
