### ISSUE TITLE
Quic不能工作

### ISSUE THREAD

**Issue by txdywy** [xausky/ShadowsocksGostPlugin#20]
服务端也没有日志输出.tcpdump看到很多udp流量过来.gost本身的client模式没问题

**Comment by nsfwdocnet** [comment]
借楼，gost已经升级到2.9.2了，可否更新一下这个好用的插件，谢谢

**Comment by txdywy** [comment]
期待

nsfw.net <notifications@github.com> 于 2020年1月25日周六 下午3:07写道：

**Comment by xausky** [comment]
更新了新的 2.11.0 版本可以试试
