### ISSUE TITLE
未知插件gost

### ISSUE THREAD

**Issue by vocano** [xausky/ShadowsocksGostPlugin#21]
配置好ss和插件gost后，点击连接，toast：
`后台服务启动失败：无法连接远程服务器：未知插件gost`
SS下载https://github.com/shadowsocks/shadowsocks-android
gost安装：2.8.1-3 版本
设备：华为P20pro

请问这是SS+gost插件配置问题吗？
gost服务器设置正确，其他客户端连接没问题。

**Comment by xausky** [comment]
https://github.com/xausky/ShadowsocksGostPlugin/issues/18#issuecomment-593039356
这个试试
