### ISSUE TITLE
使用插件连接失败

### ISSUE THREAD

**Issue by WANGManho** [xausky/ShadowsocksGostPlugin#23]
开启插件后，显示后台服务启动失败，无法连接远程服务器。

**Comment by dilide** [comment]
用的是 MIUI 吗？这个好像是因为 MIUI 新增加了应用行为记录，禁止了链式启动（也就是说 shadowsocks 无法启动插件），我还不知道该如何设置关闭……
你解决这个问题了吗？

**Comment by dilide** [comment]
> 开启插件后，显示后台服务启动失败，无法连接远程服务器。

用的是 MIUI 吗？这个好像是因为 MIUI 新增加了应用行为记录，禁止了链式启动（也就是说 shadowsocks 无法启动插件），我还不知道该如何设置关闭……
你解决这个问题了吗？

**Comment by dev4u** [comment]
> 开启插件后，显示后台服务启动失败，无法连接远程服务器。

need more info

**Comment by ahrimango** [comment]
同样的问题。弹这个错误：【后台服务启动失败：libss-local exits too fast(exit code: 255)】

**Comment by SinyoWong** [comment]
gost插件好像不支持 https 代理？

**Comment by xausky** [comment]
这个问题是因为部分系统限制不允许后台启动原生 Linux 进程，导致的这个问题，在设置里面也许可能找到相关选项配置。
