### ISSUE TITLE
配置成功后，使用时报错了unable to resolve host cp.cloudflare.com

### ISSUE THREAD

**Issue by 03128crz** [xausky/ShadowsocksGostPlugin#24]
同一个配置，在windows上没问题，在手机上出错了

![Screenshot_20200603_093944_com github shadowsocks](https://user-images.githubusercontent.com/3424553/83586357-c81c9480-a57e-11ea-8260-2228e17f06fc.jpg)

**Comment by SinyoWong** [comment]
可以看下你的配置么？敏感信息可以打下码

**Comment by Sollovin** [comment]
我也遇到了这个问题，系统是 android 10, shadowsocks 版本 5.1.1，插件是最新的release。
![Screenshot_20200820103039](https://user-images.githubusercontent.com/15872396/90710251-917a2e80-e2d0-11ea-8aa1-3b9a15f182e6.jpg)
![Screenshot_20200820103108](https://user-images.githubusercontent.com/15872396/90710252-917a2e80-e2d0-11ea-964b-75b408f0e0f0.jpg)

**Comment by Sollovin** [comment]
补充一下，我的服务器直接访问不到，所以我用 wss 套了个 cloudflare 的域名解析，gost 服务端同时设置了探测防御。

**Comment by xausky** [comment]
应该是 cloudflare 域名无法被系统 DNS 解析，你可以在 Server 那里随便填一个可以连通的域名，然后服务器的域名填到插件配置里面

**Comment by Sollovin** [comment]
我把Server设置成了 baidu.com, Port设置成了80，还是不行，相同的报错。

**Comment by SinyoWong** [comment]
路由要改为 GFW 列表




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Hollow"<notifications@github.com&gt;; 
发送时间: 2020年9月4日(星期五) 中午11:01
收件人: "xausky/ShadowsocksGostPlugin"<ShadowsocksGostPlugin@noreply.github.com&gt;; 
抄送: "Sinyo"<591200204@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [xausky/ShadowsocksGostPlugin] 配置成功后，使用时报错了unable to resolve host cp.cloudflare.com (#24)





 
我把Server设置成了 baidu.com, Port设置成了80，还是不行，相同的报错。

**Comment by Sollovin** [comment]
> 路由要改为 GFW 列表

路由用的就是这个。

**Comment by SinyoWong** [comment]
我的连接成功，但不能上外网，跟没连一样，电脑上没问题。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Hollow"<notifications@github.com&gt;; 
发送时间: 2020年9月4日(星期五) 下午2:53
收件人: "xausky/ShadowsocksGostPlugin"<ShadowsocksGostPlugin@noreply.github.com&gt;; 
抄送: "Sinyo"<591200204@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [xausky/ShadowsocksGostPlugin] 配置成功后，使用时报错了unable to resolve host cp.cloudflare.com (#24)





  
路由要改为 GFW 列表
  
路由用的就是这个。

**Comment by andrey-martianov** [comment]
I have same problem connecting from Russia to Germany. 
Any info in English , please ?

**Comment by SinyoWong** [comment]
I didn't make it through ,
but why Russia to Germany need this app ?&nbsp;



---原始邮件---
发件人: "Andrey Martianov"<notifications@github.com&gt;
发送时间: 2020年10月24日(周六) 上午9:43
收件人: "xausky/ShadowsocksGostPlugin"<ShadowsocksGostPlugin@noreply.github.com&gt;;
抄送: "Sinyo"<591200204@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [xausky/ShadowsocksGostPlugin] 配置成功后，使用时报错了unable to resolve host cp.cloudflare.com (#24)




 
I have same problem connecting from Russia to Germany.
 Any info in English , please ?

**Comment by xausky** [comment]
The server on ss must fill in a directly accessible domain name, because the domain name will be dns resolved before the proxy is started.
ss 上 server 必须填写可直接访问的域名，因为启动代理前会对此域名进行 dns 解析。

**Comment by hehehuai** [comment]
使用4.8.7版本可以

**Comment by qi20172017** [comment]
像楼上所说用4.8.7版本可以
As mentioned above, use version 4.8.7

**Comment by luiguangguan** [comment]
我遇到这个问题是因为我的ss服务器使用了域名，而域名中存在下划线“_”, 似乎下划线在域名中的被允许性存在争议，反正不用_下划线的域名作为ss服务器域名就OK了

**Comment by kaisame** [comment]
更改下服务端的端口就好了

**Comment by panlina** [comment]
> 我遇到这个问题是因为我的ss服务器使用了域名，而域名中存在下划线“_”, 似乎下划线在域名中的被允许性存在争议，反正不用_下划线的域名作为ss服务器域名就OK了

我是没有下划线的域名，也报这个错误，改成ip地址就好了

**Comment by alfonsinaaaa** [comment]
> 更改下服务端的端口就好了

我也是这样处理以后就行了，但是并不知道原理是什么

**Comment by dablelv** [comment]
> 路由要改为 GFW 列表
> […](#)

Android 端的还真是这个原因，但是还是有两个问题i:

1.背后原理是什么？

2.Windows 端的 Shadowsocks 客户端并没有这个配置，怎么办？
