### ISSUE TITLE
一点建议：配置可进一步简化+提升性能

### ISSUE THREAD

**Issue by xiaokaixuan** [xausky/ShadowsocksGostPlugin#25]
服务器：`gost.exe -L=ss+mws://chacha20:ss123456@:8888`

客户端：`gost.exe -L=tcp://127.0.0.1:8887 -F=forward+mws://xx.xx.xx.xx:8888`

然后shadowsocks可直接chacha20:ss123456连接127.0.0.1:8887，或者`gost.exe -L=:1080 -F=ss://chacha20:ss123456@127.0.0.1:8887`

**Comment by xausky** [comment]
但是这样需要服务器端只能使用 ss 协议，感觉有点失去了 gost 的优势，但是确实具有性能上的优势
