### ISSUE TITLE
无法指定kcp配置文件

### ISSUE THREAD

**Issue by kinsan2007** [xausky/ShadowsocksGostPlugin#26]
例子是这样的
-F ss+kcp://aes:password@server_ip:server_port 的情况下正常使用
但尝试指定 kcp 配置文件时失败
-F ss+kcp://aes:password@server_ip:server_port?c=/storage/emulated/0/kcp.conf
文件路径没有问题
请问是插件本身不支持吗？

**Comment by xiaokaixuan** [comment]
@kinsan2007 这个可能是读取权限的问题，用logcat看下就知道了。

**Comment by xausky** [comment]
应该是读取权限问题，SS本身可能没有读取内部存储的权限，还是吧配置编写到命令行吧
