### ISSUE TITLE
请问会加入ss2的支持吗？

### ISSUE THREAD

**Issue by Akitora-R** [xausky/ShadowsocksGostPlugin#3]
测试了一下，好像ss2还不支持的样子。
以及有点好奇，本地ss为何是chacha20，如果使用rc4-md5是不是会更快一些呢？

**Comment by xausky** [comment]
本地默认使用chacha20，其实本来可以配置的，但是为了简化配置就写死了，chacha20在移动设备上的性能应该还可以，这个的主要瓶颈也不是加密。

**Comment by Akitora-R** [comment]
发现如果服务器填域名，端口443，通过nginx反代，插件设置：
-F ss+mwss://rc4-md5:密码@#SS_HOST:#SS_PORT?ip=*********&path=/****/
这样似乎无法连接

**Comment by xausky** [comment]
README 里面使用方法第四点：注意使用#SS_HOST参数会先对填写的主机名进行DNS解析后才传递，如果是与主机名相关的远程协议比如ws协议必须之间在参数里面配置
这个过程是小飞机做的，插件只能拿到IP了，所以无法正确设置HTTP Host Header，可以不用#SS_HOST变量，直接把域名写插件配置（这样配置会固定使用114DNS）。

**Comment by Akitora-R** [comment]
可以用了，非常感谢。
只是……请问有打算优化一下耗电吗…稍微有点大…
![photo_2019-07-02_19-51-47](https://user-images.githubusercontent.com/52414064/60510770-d923ac80-9d02-11e9-864e-600be99c4f99.jpg)

**Comment by xausky** [comment]
耗电量问题不知道怎么解决，也许换个算法会好点。
