### ISSUE TITLE
希望支持https协议

### ISSUE THREAD

**Issue by 2Dou** [xausky/ShadowsocksGostPlugin#30]
在安卓上没找到合适的https代理软件，希望能支持https协议

**Comment by 2Dou** [comment]
看了源码，加密选RC4-MD5，密码填:gost；然后参数里面填好https的链接就可以了

**Comment by 2Dou** [comment]
> Dou哥你好，请问下参数里该怎么配置https链接呢？
> 我输入过很多方式都链接不上（windows端可以连接成功）：
> -F https://xxx:xxxx@xxx.xxxx.xxx:443
> -F ss+mws://RC4-MD5:https://xxx:xxxx@xxx.xxxx.xxx:443
> -F https://xxx:xxxx@#SS_HOST:#SS_PORT
> -F ss://RC4-MD5:https://xxx:xxxx@#SS_HOST:#SS_PORT
> ...

我的参数就是`-F https://xxx:xxxx@#SS_HOST:#SS_PORT`。
然后SS本身加密方式用`RC4-MD5`，密码用`gost`，见`https://github.com/xausky/ShadowsocksGostPlugin/blob/master/gost.patch`第30行。

**Comment by xinlmain** [comment]
> > Dou哥你好，请问下参数里该怎么配置https链接呢？
> > 我输入过很多方式都链接不上（windows端可以连接成功）：
> > -F https://xxx:xxxx@xxx.xxxx.xxx:443
> > -F ss+mws://RC4-MD5:https://xxx:xxxx@xxx.xxxx.xxx:443
> > -F https://xxx:xxxx@#SS_HOST:#SS_PORT
> > -F ss://RC4-MD5:https://xxx:xxxx@#SS_HOST:#SS_PORT
> > ...
> 
> 我的参数就是`-F https://xxx:xxxx@#SS_HOST:#SS_PORT`。
> 然后SS本身加密方式用`RC4-MD5`，密码用`gost`，见`https://github.com/xausky/ShadowsocksGostPlugin/blob/master/gost.patch`第30行。

还是不行呀，Shadowsocks有版本要求吗？

**Comment by rocinn** [comment]
牛，按您说的连上了
