### ISSUE TITLE
ss报错

### ISSUE THREAD

**Issue by kinsui** [xausky/ShadowsocksGostPlugin#4]
插件配置为：`-F=mwss://domain.com:2019?path=/test`
报错信息如图：
![Screenshot_2019-07-03-00-08-04-177](https://user-images.githubusercontent.com/23612126/60528505-23b72000-9d27-11e9-86f0-324e80130a73.png)
ps，我发现插件配置信息会自动在保存后给path后面加上‘\’，如上配置保存后就变成了：
`-F=mwss://domain.com:2019?path\=/test`

**Comment by xausky** [comment]
我测试了一下带=号的参数好像没有问题，不知道从哪里入手这个bug

**Comment by badaoshen** [comment]
> 我测试了一下带=号的参数好像没有问题，不知道从哪里入手这个bug

会不会是安卓版本的原因，安卓6.0

**Comment by UnderCooled** [comment]
我发现写成 `-F ` 而不是 `-F=` 后面参数的等号就不会被加上斜杠转义了

**Comment by xausky** [comment]
在模拟器上测试6.0版本确实不行，应该还是系统版本问题

**Comment by nsfwdocnet** [comment]
ss客户端配置:
服务器:abc.xyz
端口:443
密码:空
加密方式:rc4-md5
插件配置:-F mwss://#SS_HOST:#SS_PORT

服务器部署应该是成功运行起来的:404 page not found

结果，客户端无法连接远程服务器。没有日志，只有这些模糊的描述

**Comment by UnderCooled** [comment]
> 手机系统是5.1
> 
> ss客户端配置:
> 服务器:abc.xyz
> 端口:443
> 密码:空
> 加密方式:rc4-md5
> 插件配置:-F mwss://#SS_HOST:#SS_PORT
> 或者-F mwss://abc.xyz:443
> 
> 服务器部署应该是成功运行起来的:404 page not found
> 
> 结果，客户端无法连接远程服务器。没有日志，只有这些模糊的描述

2.8.1 版本密码要填 `gost`

**Comment by nsfwdocnet** [comment]
谢谢提醒，正使用中
