### ISSUE TITLE
请问 gost -L=:8080 -F=kcp://server_ip:8388 这样的配置 我该怎么写？

### ISSUE THREAD

**Issue by kinsan2007** [xausky/ShadowsocksGostPlugin#5]
我直接使用可 kcp的默认配置 一下是gost readme对kcptun描述的引用：
“
KCP
gost对KCP的支持是基于kcp-go和kcptun库。
服务端:
gost -L=kcp://:8388
客户端:
gost -L=:8080 -F=kcp://server_ip:8388
"
请问我该如何修改我的配置
-F=kcp://server_ip:8388 的设置是无法使用的

**Comment by xausky** [comment]
插件配置里面写：`-F=kcp://server_ip:8388`
Shadowsocks界面配置chacha20加密和ss123456密码

**Comment by kinsan2007** [comment]
正如我上面说的，-F=kcp://server_ip:8388 并无法使用
（我已正确设置了chacha20 和ss123456）

**Comment by kuaizi** [comment]
IP设置服务器ip
端口设置kcp端口

gost插件设置-F kcp://#SS_HOST:#SS_PORT
没有问题

这是我的设置
ss://Y2hhY2hhMjA6c3MxMjM0NTY@地址:端口?plugin=gost%3B-F%20kcp%3A%2F%2F%23SS_HOST%3A%23SS_PORT#kcp

**Comment by kinsan2007** [comment]
谢谢 在ss中正确设置了ip和port后，才能正常使用
（端口和地址并不能随便填写）

**Comment by xausky** [comment]
如果IP和PORT写到插件配置里面上面的确实可以乱填的，因为上面填的作用就是会映射到#SS_HOST和#SS_PORT变量。
