### ISSUE TITLE
安装失败:存在同名的数据库

### ISSUE THREAD

**Issue by nsfwdocnet** [xausky/ShadowsocksGostPlugin#7]
或许这不是一个issue。ShadowsocksGoProxyPlugin (https://github.com/snail007/goproxy-ss-plugin-android) 与作者你的ShadowsocksGostPlugin不能共存。

系统提示:安装失败:存在同名的数据库。

想问问作者，有没有方法让它们安装共存。
谢谢

**Comment by xausky** [comment]
这确实是个问题，等我有时间就去看看

**Comment by nsfwdocnet** [comment]
通过搜索似乎被我取巧解决了，只需反编译"
AndroidManifest.xml"，把这个值android:authorities="$FULLY_QUALIFIED_NAME_OF_YOUR_CONTENTPROVIDER"改为不与前者相同的任意字符即可，比如android:authorities="test"。😂

**Comment by xausky** [comment]
是我和那个插件都写错了，这里应该改为自己的唯一名称的，下版本修复

**Comment by nsfwdocnet** [comment]
好
