### ISSUE TITLE
如何使用自定义证书？

### ISSUE THREAD

**Issue by UnderCooled** [xausky/ShadowsocksGostPlugin#8]
在 PC 上使用参数是这样的：`?cert=./full_chain.pem&key=./private.key` ，放置于 gost.exe 所在文件夹可以使用。

**Comment by xausky** [comment]
放到手机存储中然后配置路径（比如 /sdcard/private.key），确保小飞机有读取内部存储权限，没有实际测试过，只是理论应该可以。

**Comment by segfault-bilibili** [comment]
有空可以帮忙测试一下 https://github.com/segfault-bilibili/ShadowsocksGostPlugin/releases/tag/v2.11.1-gui
