### ISSUE TITLE
强烈建议重新写一下使用说明

### ISSUE THREAD

**Issue by ddgweb** [xausky/ShadowsocksGostPlugin#9]
明明很简单，但是根据使用说明看晕了，建议修改为：
1、安装之后，无需其他启用界面，需要在ss内重新添加服务器，勾选插件启动生效。
2、正确输入IP和端口，加密方式选择RC-MD5，密码输入gost。
3、在插件参数内，修改协议和加密方式，后面的#hostip和#port不需要修改

这样写，大家都能看懂。

**Comment by xausky** [comment]
这样写其实是不全面的，后面关于 DNS 和域名配置的说明是必要的

**Comment by ddgweb** [comment]
> 这样写其实是不全面的，后面关于 DNS 和域名配置的说明是必要的

能不能请教一下，我依葫芦画瓢，在ss-windows版本试图用gost插件，填入相关启动参数以后，是能创建gost进程，参数也对，但是就是ss没办法成功访问网页，不知道哪里出了问题

**Comment by xausky** [comment]
是你自己编译的 Windows 版 gost shadowsocks 插件么 @ddgweb

**Comment by ddgweb** [comment]
> 是你自己编译的 Windows 版 gost shadowsocks 插件么 @ddgweb

额，还需要另外编译吗？根据shadowsocks的指导文档，我直接在windows-shadowsocks版本中，编辑服务器信息，添加了gost最新版64位exe文件，配置启动参数

**Comment by xausky** [comment]
这个可以，但是配置要对，可以看看gost的日志检查

**Comment by ddgweb** [comment]
我配置的，访问网页显示500，gost日志没有什么有效的信息，能否给些建议？

服务器：
gost -L=ss+kcp://chacha20:123456@:1080

客户端：
SS，配置参数：
-L :%SS_LOCAL_PORT% -F ss+kcp://chacha20:123456@%SS_REMOTE_HOST%:%SS_REMOTE_PORT%

**Comment by xausky** [comment]
客户端配置不对，应该是
-L ss+tcp://<method>:<password>@%SS_LOCAL_HOST%:%SS_LOCAL_PORT% -F ss+kcp://chacha20:123456@%SS_REMOTE_HOST%:%SS_REMOTE_PORT%
然后 ss 配置加密方法 <method> 和密钥 <password>

**Comment by xausky** [comment]
还有 PC 端加密推荐 aes-256-gcm 一个是强度高，二是有CPU指令集支持，速度快

**Comment by ddgweb** [comment]
> 还有 PC 端加密推荐 aes-256-gcm 一个是强度高，二是有CPU指令集支持，速度快

能兼容手机端吗，我手机和pc都一台服务器，Android用你的插件

**Comment by xausky** [comment]
手机也用的话chacha20也可以

**Comment by ddgweb** [comment]
> 手机也用的话chacha20也可以，你有支持kcp的服务器的话为什么不直接部署 ss + kcptun，而要用 gost

gost部署比较简单？命令行一句话就搞定了。。。

**Comment by xausky** [comment]
也是

**Comment by ddgweb** [comment]
> 也是

kcptun和gost有差？在效率和性能方面

**Comment by xausky** [comment]
差不多吧，和带宽对比，这点性能并不是瓶颈

**Comment by ddgweb** [comment]
> 客户端配置不对，应该是
> -L ss+tcp://`<method>`:`<password>`@%SS_LOCAL_HOST%:%SS_LOCAL_PORT% -F ss+kcp://chacha20:123456@%SS_REMOTE_HOST%:%SS_REMOTE_PORT%
> 然后 ss 配置对应的加密方法 `<method>` 和密钥 `<password>`

我按你的参数配置服务器，发现ss并没有成功，查看日志发现：

[2019-09-26 14:33:29] Started SIP003 plugin for *****:1080 on 127.0.0.1:12063 - PID: 10812
[2019-09-26 14:33:30] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2019-09-26 14:33:30] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)

同时我查看了一下任务管理器，发现并没有启动gost.exe的进程。

**Comment by xausky** [comment]
不知道了，我并没有在 Windows 上面使用过，Windows 上面为什么不直接使用 gost 就好了

**Comment by kinsan2007** [comment]
记得gost 不能使用ss+kcp 你再去看看readme吧

**Comment by ddgweb** [comment]
> 记得gost 不能使用ss+kcp 你再去看看readme吧

不用SS，直接 gost就能连上，当然能用ss+kcp

**Comment by kinsan2007** [comment]
我说的不够清楚 gost 不支持 ss+kcp 这样的参数组合

**Comment by ddgweb** [comment]
> 我说的不够清楚 gost 不支持 ss+kcp 这样的参数组合

如果gost不支持 ss+kcp，我现在可能没办法回你评论，我客户端gost直连服务端gost是没问题的，但是用ss配插件不行。

**Comment by kinsan2007** [comment]
-L=ss+kcp://chacha20:123456@:1080     ss+kcp是不被支持的

**Comment by ddgweb** [comment]
> 查了下 最新版是支持ss+kcp的，打扰了

哈哈，帮忙看下ss的配件和参数为啥不行

**Comment by kinsan2007** [comment]
手机上测试过可的 服务器上用 gost -L  ss +kcp  手机上使用 ss 加kcp插件（并不使用gost插件）

**Comment by ddgweb** [comment]
> 手机上测试过可的 服务器上用 gost -L ss +kcp 手机上使用 ss 加kcp插件（并不使用gost插件）
> 电脑上你也使用kcptun插件好了

我有kcp插件，但是配置参数总配不正确，总连不上，请教一下给个参考？

**Comment by kinsan2007** [comment]
我为了手机上输入方便 全用默认的
服务器上开-L ss+kcp://chacha20:123456@:50000
手机上的话全删掉就成 电脑上好久没用了啊

**Comment by ayucapal** [comment]
> 
> 
> 明明很简单，但是根据使用说明看晕了，建议修改为：
> 1、安装之后，无需其他启用界面，需要在ss内重新添加服务器，勾选插件启动生效。
> 2、正确输入IP和端口，加密方式选择RC-MD5，密码输入gost。
> 3、在插件参数内，修改协议和加密方式，后面的#hostip和#port不需要修改
> 
> 这样写，大家都能看懂。

我说实话, 我读了几遍没明白"gost密码"是哪个密码, 一直连不通, 看了你写的"密码输入gost"才恍然大悟, 连通了.

**Comment by ddgweb** [comment]
> > 明明很简单，但是根据使用说明看晕了，建议修改为：
> > 1、安装之后，无需其他启用界面，需要在ss内重新添加服务器，勾选插件启动生效。
> > 2、正确输入IP和端口，加密方式选择RC-MD5，密码输入gost。
> > 3、在插件参数内，修改协议和加密方式，后面的#hostip和#port不需要修改
> > 这样写，大家都能看懂。
> 
> 我说实话, 我读了几遍没明白"gost密码"是哪个密码, 一直连不通, 看了你写的"密码输入gost"才恍然大悟, 连通了.

作者写的那个“使用说明”，太过于啰嗦，挺简单的事情，讲的特别复杂

**Comment by mmfan** [comment]
gost211.exe -L=:1090 -F=socks5+wss//***.***:443 在插件中能使用不？谢谢 在插件中是不是只写-f（含-f）后面的

**Comment by mmfan** [comment]
插件内核是不是该更新了！谢谢
